#+title: Papers Published
{{<rawhtml>}}
<style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    span.underline{text-decoration: underline;}
    div.column{display: inline-block; vertical-align: top; width: 50%;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
  </style>
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.min.js"></script>
  <![endif]-->
<div id="refs" class="references hanging-indent" role="doc-bibliography">
<div id="ref-day20emoji">
<p><strong>Day, Alex</strong>, Chris Mankos, Soo Kim, and Jody Strausser. 2020. “CoNFET: An
    English Sentence to Emojis Translation Algorithm.” In <em>Proceedings of the
    35th Annual Spring Conference of the Pennsylvania Computer and Information
    Science Educators</em>. Pennsylvania Computer Information Science Educators.
    <strong>Forthcoming</strong> [<a
        href="https://github.com/AlexanderDavid/Sentence-to-Emoji-Translation">code</a>]
        [<a href="/pdf/emoji.pdf">pdf</a>] [<a href="/ppt/SentenceEmojiTranslation.pptx">slides</a>]</p>
</div>
<div id="ref-day19summary">
<p><strong>Day, Alex</strong>, and Soo Kim. 2019. “A Comparison of Automatic Extractive Text
    Summarization Techniques.” In <em>Proceedings of the 34th Annual Spring
    Conference of the Pennsylvania Computer and Information Science Educators</em>,
        98, 102. Pennsylvania Computer Information Science Educators. [<a
        href="https://github.com/AlexanderDavid/AutomaticExtractiveSummarization">code</a>]
        [<a href="/pdf/extractive.pdf">pdf</a>] [<a href="https://slides.com/alexday-2/a-comparison-of-automatic-extractive-summarization-techniques/#/">slides</a>]</p>
</div>
</div>
{{</rawhtml>}}

