#+TITLE: Talks I've Given
{{<rawhtml>}}
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    span.underline{text-decoration: underline;}
    div.column{display: inline-block; vertical-align: top; width: 50%;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
  </style>
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.min.js"></script>
  <![endif]-->
<div id="refs" class="references hanging-indent" role="doc-bibliography">

<div id="ref-sentence_compression_penn_york">
<p><strong><strong>Day, Alex</strong></strong>, Chris Mankos, Soo Kim, and Jody Strausser. November 2019.
“Sentence Compression Using Emoji Summarization.” <em>Penn-York Undergraduate
Research Conference</em> at Clarion University of Pennsylvania. [<a
href="/assets/pdf/PennYorkSentenceCompression.pptx">slides</a>] [<a href="https://github.com/AlexanderDavid/Sentence-to-Emoji-Translation">code</a>]</p> </div>

<div id="ref-DSML4Kidz">
<p>Hum, Sam, <strong><strong>Day, Alex</strong></strong>, and Wagner, Riley. August 2019. “Verification and Creation
of Autonomous Vehicle Trajectories for Non-Experts with Reactive Design-Time
Feedback and Sensor-Based Response.” <em>Undergraduate Research Opportunities
Consortium</em> at the University of Arizona. [<a
href="https://github.com/jmscslgroup/DSML4KidsReachabilityServer">code</a>]</p>
</div>

<div id="ref-unittest">
<p><strong><strong>Day, Alex</strong></strong>. April 2019. “How to Utilize the UnitTest Module in Python 3.”
Clarion University of Pennsylvania. [<a href="https://slides.com/alexday-2/unit-testing-with-python#/">slides</a>]</p> </div>

<div id="ref-github">
<p><strong>Day, Alex</strong>. October 2018. “Introduction to Git, GitHub, and Contributing to
Open Source.” <em><a
href="https://hacktoberfest.digitalocean.com/">Hacktoberfest</a> Seminar</em> at
Clarion University of Pennsylvania. [<a href="https://docs.google.com/presentation/d/1Tfy2o1SDD3iuAgrZeh2VlTE1UjvXSqhFFysAixL5D1Q/edit?usp=sharing">slides</a>]</p>
</div>

<div id="ref-vex">
<p><strong>Day, Alex</strong>. April 2018. “The VEX Robotics Programming Language for Competing.”
<em>Robotics Competition Open Day</em> at Clarion University of Pennsylvania. [<a
href="https://docs.google.com/presentation/d/1UgE_fQgLpRCREdhXa2e7Fw5AeeDjXNnN0T9V1uBvl-g/edit?usp=sharing">slides</a>]</p> </div>

</div>
{{</rawhtml>}}
